.gitignore, .storybook/main.ts, .storybook/preview.tsx, package.json, src/components/Common/Button/Button.stories.tsx, src/components/Common/Button/index.tsx, src/components/Common/ProgressBar/ProgressBar.stories.tsx, src/components/Common/ProgressBar/index.tsx, src/pages/_app.tsx, src/styles/GlobalStyles.tsx, src/styles/utils/toCssVar.ts, tsconfig.json, yarn.lock
- #7 
- `Button` 컴포넌트 추가
- `ProgressBar` 컴포넌트 추가
- storybook에서 path alias를 resolve하지 못하여, storybook의 webpack config 확장
- storybook에서 css prop을 사용하지 못하여, storybook의 babel config 확장
- 글로벌 스타일 추가 
- 상세 디자인이 나오면 컴포넌트의 `prop`을 일부 수정해야 합니다.
=> `Button` 컴포넌트, `ProgressBar` 컴포넌트 추가

src/styles/utils/fontCss.ts, src/styles/utils/index.ts, src/styles/utils/pxToRem.ts
- #20 
- Font CSS 유틸리티 추가
- `pxToRem`추가
=> Font Utility 추가

src/components/LunchCard/index.tsx, src/hooks/useMSW.ts, src/mocks/handlers/auth/index.ts, src/mocks/handlers/examples/index.ts, src/mocks/index.ts, src/pages/_app.tsx, src/services/auth/apis.ts, src/utils/axios.ts, src/utils/constants.ts, src/utils/index.ts, src/utils/misc.ts
- #22 
- MSW handler endpoint 업데이트
- MSW를 서버사이드에서 사용하기 위해서는 mock handler의 endpoint가 절대경로여야해서 `API_URL`추가
- 경로 합치기 위해서 `composeUrls`추가 
- axios custom instance 생성
- 페이지 렌더링전에 MSW 초기화 보장되게 변경
- `useMSW`추가
=> MSW config 업데이트, `axios`커스텀 인스턴스 추가

src/components/Common/Gnb/index.tsx, src/components/Layout/MainLayout.tsx, src/styles/GlobalStyles.tsx, src/styles/utils/constants.ts, src/styles/utils/flexCss.ts, src/styles/utils/index.ts
- #32 
- `<Gnb />` 구현
- `flexCss` 추가 (emotion utility)
- style 관련 constants 추가
- `fontCss`쪽에서 제가 실수를 하나 한게 있어서, [이 PR](https://github.com/SSAF-SOUND/ssaf-sound-fe/issues/30)이 반영되어야 `<Gnb />`컴포넌트가 제대로 나옵니다.
=> `<Gnb />`, style관련 유틸리티 추가

src/components/Common/Avatar/Avatar.stories.tsx, src/components/Common/Avatar/AvatarGroup.tsx, src/components/Common/Avatar/SingleAvatar.tsx, src/components/Common/Avatar/index.tsx, src/components/Common/index.ts, src/styles/utils/fontCss.ts
- #36 
- 아바타 구현
- 아바타 그룹 구현 (zIndex관련 부분으로 구현)
=> Avatar, Avatar Group Component

src/components/Common/SelectBox/SelectBox.stories.tsx, src/components/Common/SelectBox/index.tsx, src/styles/GlobalStyles.tsx, src/styles/utils/themeColorVars.ts
=> `<SelectBox />` 업데이트

src/mocks/handlers/index.ts, src/mocks/handlers/recruit/data.ts, src/mocks/handlers/recruit/index.tsx, src/pages/recruit/[id].tsx, src/pages/recruit/index.tsx, src/react-query/common/queryKeys.ts, src/services/recruit/apis.ts, src/services/recruit/index.ts
=> Recruit API & Msw

package.json, src/components/Common/Toast/ServerErrorToast.tsx, src/components/Common/Toast/Toast.stories.tsx, src/components/Common/Toast/index.tsx, src/components/Common/index.ts, src/pages/_app.tsx, src/utils/handleAxiosError.tsx, yarn.lock
- #60 
- `<Toast.ServerError />` 를 추가하였습니다.
- `handleAxiosError`를 만든 이유는 이슈를 참고해주세요.
=> `<Toast />`, `handleAxiosError`

src/components/Common/Icon/index.tsx, src/components/ProjectInfo/Info.tsx, src/components/ProjectInfo/ProjectInfo.stories.tsx, src/components/ProjectInfo/index.tsx, src/components/ProjectInfo/utils.ts, src/mocks/handlers/recruit/index.tsx, src/services/recruit/apis.ts
- #56 
- 피그마의 variant를 일단 신경안쓰고 작업했습니다.
- 피그마 상, 제목 + Name 택이 달린 부분이 있던지 없던지가 갈리는 것 같은데 별개의 컴포넌트로 빼는게 맞다고 생각했기 때문이에요..! (콜라의 의견이 궁금합니다!)
-
=> Project Info 컴포넌트

package.json, src/components/Common/Checkbox/Checkbox.stories.tsx, src/components/Common/Checkbox/index.tsx, src/components/Common/Icon/index.tsx, yarn.lock
=> `<Checkbox />`

package.json, src/components/Common/Toggle/Toggle.stories.tsx, src/components/Common/Toggle/index.tsx, src/components/Common/index.ts, src/styles/GlobalStyles.tsx, src/styles/utils/palettes.ts, yarn.lock
=> `<Toggle />`

package.json, src/components/Common/Tabs/Border.tsx, src/components/Common/Tabs/List.tsx, src/components/Common/Tabs/Tabs.stories.tsx, src/components/Common/Tabs/Trigger.tsx, src/components/Common/Tabs/index.tsx, src/components/Common/index.ts, yarn.lock
- #81 
- Tabs 구현
- 사용은 래딕스처럼 하시면됩니다 ! 
-
=> `<Tabs />`

package.json, src/components/SkillBadge/SkillBadge.stories.tsx, src/components/SkillBadge/index.tsx, yarn.lock
- #91 
- 스킬배지 컴포넌트 추가
- 그런데 내부적으로 `data-state="active" 등 래딕스처럼 사용할 필요가 있는건지 궁금한 것도 있어요
-
=> `<SkillBadge />`

src/styles/utils/hideScrollBar.ts, src/styles/utils/lineClamp.ts
=> `hideScrollBar, lineClamp`

src/mocks/handlers/recruit/index.tsx, src/pages/recruit/index.tsx, src/react-query/common/queryKeys.ts, src/services/recruit/apis.ts, src/services/recruit/utils/types.ts
- #104 
- 리쿠르트들을 불러오는 API 타입을 정의했어요.
- 모킹함수를 추가했어요. (데이터는 일단 노션걸 긁어왔답니다!)
=> Recruit API 추가

src/components/SquareAvatar/SquareAvatar.stories.tsx, src/components/SquareAvatar/Vacant.tsx, src/components/SquareAvatar/index.tsx, src/styles/utils/palettes.ts
- #68 
- 스퀘어 아바타와, 스토리를 추가했습니다.
- 최대 글자수 길이 11자를 맞춰 진행했어요.
- 인증이 되었는지 전공타입이 있는지에 맞춰 트랙 아이콘을 조절할 수 있도록 했어요.
=> `<SquareAvatar />`

src/components/Common/Avatar/SingleAvatar.tsx, src/components/Dday/index.tsx, src/components/RecruitCard/Common/RecruitSkills.tsx, src/components/RecruitCard/RecruitCard.stories.tsx, src/components/RecruitCard/Small/RecruitBadge.tsx, src/components/RecruitCard/Small/index.tsx, src/components/RecruitCard/Wide/RecruitParticipants.tsx, src/components/RecruitCard/Wide/RecruitTitle.tsx, src/components/RecruitCard/Wide/WithMyBadge.tsx, src/components/RecruitCard/Wide/index.tsx, src/components/RecruitCard/index.tsx, src/styles/utils/index.ts
=> `<RecruitCard />` reopen

src/components/Common/Gnb/index.tsx, src/components/Common/Modal/Core.tsx, src/components/Common/Toggle/index.tsx, src/components/MyInfoSettings/NavItem.tsx, src/components/MyInfoSettings/NavTitle.tsx, src/components/MyInfoSettings/index.ts, src/components/NavigationGroup/index.tsx, src/components/PortfolioForm/index.tsx, src/components/TitleBar/DefaultTitleBar.tsx, src/components/TitleBar/FormTitleBar.tsx, src/components/TopBar/index.tsx, src/mocks/handlers/auth/index.ts, src/pages/_app.tsx, src/pages/auth/register/index.tsx, src/pages/profile/[id]/index.tsx, src/pages/profile/myinfo-settings/edit/index.tsx, src/pages/profile/myinfo-settings/index.tsx, src/react-query/common/queryKeys.ts, src/services/auth/apis.ts, src/services/auth/hooks.ts, src/styles/utils/constants.ts, src/styles/utils/fixedPosition.ts, src/styles/utils/index.ts, src/utils/axios.ts, src/utils/routes.ts, src/utils/webStorage.ts
- #118 
- 이전 PR 합쳐지면 업데이트 할게요.
=> 내 정보 수정 일부분

src/mocks/handlers/recruit/data.ts, src/mocks/handlers/recruit/index.tsx, src/react-query/common/queryKeys.ts, src/services/recruit/apis.ts
- #125
- 간단한 PR입니다!
- members 관련 mock Data, handler, api 타입을 정리했어요.
- 기존 mock 데이터를 사용하기 편하게 조금 정리했습니다.
=> Recruit Members 관련 API 추가

src/components/RecruitCard/RecruitCard.stories.tsx, src/components/RecruitCard/Small/index.tsx, src/components/RecruitCard/Wide/index.tsx, src/components/SquareAvatar/SquareAvatar.stories.tsx, src/components/SquareAvatar/index.tsx
- #127 
- 이전에 문제되고 있었던 타입오류를 수정했습니다.
- 관련 타입들의 컨벤션을 다른 컴포넌트, 타입들과 맞춰 수정했습니다.
=> SquareAvatar, RecruitCard 관련 타입오류 수정

package.json, src/components/Common/TextArea/AutoResized.tsx, src/components/Common/TextArea/UnStyled.tsx, src/components/Common/TextArea/index.ts, src/components/Common/TextArea/useAutoReSizeTextArea.ts, src/components/Common/TextArea/utils.ts, src/components/Common/index.ts, src/hooks/index.ts, src/hooks/useAutoFocus.ts, yarn.lock
- #141 
- 코멘트 인풋에 기반이 되는 TextArea 컴포넌트
=> `<TextArea />`

src/components/Common/Avatar/SingleAvatar.tsx, src/components/Name/Name.stories.tsx, src/components/Name/index.tsx
- #71
- 익명 Name을 대응하기 위해서 prop을 하나 추가해봤습니다! 이렇게 사용해도 괜찮을지 의견 부탁드려요!
=> 익명 Name 추가

src/mocks/handlers/lunch/data.ts, src/mocks/handlers/lunch/index.ts, src/services/lunch/api.ts, src/services/lunch/index.ts
=> Lunch 관련 API 추가

src/components/Common/Tabs/TriggerWithLink.tsx, src/components/Common/Tabs/index.tsx, src/components/Layout/RecruitLayout.tsx, src/components/Layout/index.tsx, src/components/Recruit/RecruitButtons.tsx, src/components/Recruit/RecruitTabs.tsx, src/components/Recruit/ViewNumber.tsx, src/components/Recruit/index.ts, src/components/RecruitMeta/RecruitMetaTitle.tsx, src/components/RecruitMeta/RecruitTable.tsx, src/components/RecruitMeta/index.tsx, src/mocks/handlers/recruit/data.ts, src/mocks/handlers/recruit/index.tsx, src/pages/500/index.tsx, src/pages/recruit/[id].tsx, src/react-query/common/queryKeys.ts, src/services/recruit/apis.ts, src/utils/index.ts, src/utils/queryString.ts
- #134 
- #70 
- 세부 구현 사항 1
-
-
=> 리쿠르트 디테일 페이지 및 관련 컴포넌트

src/components/Common/Avatar/SingleAvatar.tsx, src/components/RecruitCard/Common/RecruitSkills.tsx, src/components/RecruitCard/Wide/RecruitParticipants.tsx, src/components/RecruitCard/Wide/RecruitTitle.tsx, src/components/RecruitCard/Wide/index.tsx
=> 리쿠르트 카드 스타일 수정, 아바타 로직 변경

package.json, src/components/CommentForm/CommentForm.mdx, src/components/CommentForm/CommentForm.stories.tsx, src/components/CommentForm/CommentFormButton.tsx, src/components/CommentForm/CommentFormCheckbox.tsx, src/components/CommentForm/CommentFormTextArea.tsx, src/components/CommentForm/index.tsx, src/components/Common/Checkbox/index.tsx, src/styles/utils/index.ts, src/styles/utils/palettes.ts, src/styles/utils/resetStyle.ts, yarn.lock
=> Comment Form

package.json, src/components/Common/Badge/Badge.stories.tsx, src/components/Common/Badge/index.tsx, src/components/Common/index.ts, src/components/SkillBadge/SkillBadgeGroup.tsx, src/components/SkillBadge/index.tsx, yarn.lock
- #175
- 리버트한 리퀘스트를 다시 보낼게요
- ToggleGroup을 이용해, 간단한 SkillBadgeGroup 작성
=> 스킬뱃지, 스킬뱃지그룹, 뱃지 컴포넌트 개편

src/hooks/index.ts, src/hooks/useQueryString.ts
- # 
- 이후 구현사항에서 계속해서 사용하는 쿼리스트링 관련 훅입니다.
=> useQueryString 훅 추가

src/components/Forms/RecruitSearchForm/index.tsx, src/hooks/index.ts, src/hooks/useQueryString.ts
=> Recruit Search Bar 컴포넌트

src/components/RecruitFilter/IsRecruitingToggle.stories.tsx, src/components/RecruitFilter/IsRecruitingToggle.tsx, src/components/RecruitFilter/RecruitFillterTabs.stories.tsx, src/components/RecruitFilter/RecruitFilterTabs.tsx, src/utils/index.ts, src/utils/stringBooleanToBool.ts
=> 리쿠르팅 필터 컴포넌트 추가

src/components/CommentForm/CommentFormCheckbox.tsx, src/components/CommentForm/CommentFormTextArea.tsx, src/components/Common/Avatar/AvatarGroup.tsx, src/components/Forms/RecruitApplyForm/Fields/ApplySelectBox.tsx, src/components/Forms/RecruitApplyForm/index.tsx, src/components/Forms/RecruitFilterForm/RecruitFormLabel.tsx, src/components/RecruitCard/Common/RecruitSkills.tsx, src/components/RecruitCard/RecruitCard.stories.tsx, src/components/RecruitCard/Wide/RecruitParticipants.tsx, src/components/RecruitFilter/IsRecruitingToggle.stories.tsx, src/components/RecruitMeta/RecruitMeta.stories.tsx, src/components/RecruitMeta/index.tsx, src/components/SquareAvatar/SquareAvatar.stories.tsx, src/hooks/useQueryString.ts, src/mocks/handlers/recruit/index.tsx, src/pages/recruit/[id].tsx, src/pages/recruit/apply/[id].tsx, src/pages/recruit/index.tsx, src/react-query/common/queryKeys.ts, src/services/lunch/apis.ts, src/services/meta/apis.ts, src/services/meta/hooks.ts, src/services/recruit/hooks.ts, src/stories/pages/recruit/RecruitDetailPage.stories.tsx
=> 린트, 타입 오류 수정

src/utils/axios.ts
- DevMode aRefresh Token이 Access Token으로 override되는 문제 해결
=> DevMode Refresh Token이 Access Token으로 override되는 문제

src/components/GlobalModal/modals.ts, src/components/ModalContent/RecruitParticipantDetail/index.tsx, src/components/ModalContent/index.ts, src/components/RecruitApplicants/RecruitApplicantsDetail/index.tsx, src/components/RecruitApplicants/RecruitMembersAvatars/index.tsx, src/components/SquareAvatar/Vacant.tsx, src/components/SquareAvatar/index.tsx, src/mocks/handlers/recruit/index.tsx, src/pages/recruits/[recruitId]/applications/mine/index.tsx, src/react-query/common/queryKeys.ts, src/services/recruit/apis/excludeRecruitParticipant.ts, src/services/recruit/apis/index.ts, src/services/recruit/hooks/useApplyRecruit.ts, src/services/recruit/hooks/useCancelRecruitApplication.ts, src/services/recruit/hooks/useExcludeRecruitParticipant.ts
=> 리쿠르팅 참여자 제외

src/components/InfiniteList/index.tsx, src/components/Profile/ProfileTabsTriggers.tsx, src/components/Profile/utils.ts, src/mocks/handlers/recruit/index.tsx, src/pages/profile/applied-recruits/[recruitCategoryName]/index.tsx, src/pages/profile/my-scraps/index.tsx, src/react-query/common/queryKeys.ts, src/services/recruit/apis/getMyScrapedRecruits.ts, src/services/recruit/apis/index.ts, src/services/recruit/hooks/useMyScrapedRecruits.ts, src/stories/pages/profile/MyProfilePage.stories.tsx, src/stories/pages/profile/MyScrapsPage.stories.tsx, src/utils/routes.ts
=> 내가 스크랩한 리쿠르팅

src/components/RecruitApplicants/RecruitApplicantsAccordion/index.tsx, src/components/RecruitApplicants/RecruitApplicantsDetail/index.tsx, src/mocks/handlers/recruit/data.ts, src/mocks/handlers/recruit/index.tsx, src/pages/recruits/[recruitId]/applications/mine/index.tsx, src/stories/pages/recruit/RecruitApplicantsPage.stories.tsx, src/stories/pages/recruit/RecruitApplicationPage.stories.tsx, src/stories/pages/recruit/RecruitApplyPage.stories.tsx, src/stories/pages/recruit/RecruitMyApplicationPage.stories.tsx, src/stories/pages/recruit/RecruitPendingApplicantsPage.stories.tsx, src/stories/pages/recruit/RecruitRejectedApplicantsPage.stories.tsx
- # 
- 신청자 목록
- 거절한 신청자 목록
- 다른 유저의 신청서 상세보기
- 내 신청서 상세보기
- 신청서 작성
=> 페이지 스토리 추가

src/components/Common/PageHeadingText/index.tsx, src/components/Common/SkillIcon/index.tsx, src/components/Common/VisuallyHidden/index.tsx, src/components/Forms/RecruitForm/Fields/Contact/index.tsx, src/components/Forms/RecruitForm/Fields/EndDate/index.tsx, src/components/Forms/RecruitForm/Fields/Participants/ProjectParticipants/ProjectParticipantsFieldRow.tsx, src/components/Forms/RecruitForm/Fields/Participants/ProjectParticipants/index.tsx, src/components/Forms/RecruitForm/Fields/QuestionToApplicants/index.tsx, src/components/TitleBar/FormTitleBar.tsx, src/mocks/handlers/recruit/apis/mockCreateRecruit.ts, src/mocks/handlers/recruit/index.tsx, src/pages/recruits/new/index.tsx, src/utils/client-routes/recruits.ts
- Form 필드의 margin 조절
- 마감일 선택 안내메세지 추가
- recruit route (client-routes)
=> 리쿠르트 생성 리팩터링

src/components/Lunch/LunchCard/LunchCard.tsx, src/components/Lunch/LunchCard/LunchCardMenuDescription.tsx, src/components/Lunch/LunchMenus/index.tsx
- 내일 점심 메뉴 투표 버튼 삭제 (오늘 점심메뉴만 가능)
=> 내일 점심 메뉴 투표 버튼 삭제

cypress.config.ts, cypress/.eslintrc.json, cypress/component/forms/RecruitForm.cy.tsx, cypress/support/component.tsx, src/components/Common/AlertText/index.tsx, src/components/Common/DatePicker/datePickerClassnames.ts, src/components/Common/DatePicker/index.tsx, src/components/Common/SelectBox/classnames.ts, src/components/Common/SelectBox/index.tsx, src/components/Editor/Editor.tsx, src/components/Editor/editorClassnames.ts, src/components/Forms/RecruitForm/Fields/Content/index.tsx, src/components/Forms/RecruitForm/Fields/Participants/ProjectParticipants/ProjectParticipantsFieldRow.tsx, src/components/Forms/RecruitForm/Fields/QuestionToApplicants/index.tsx, src/components/Forms/RecruitForm/RecruitCompleteButton.tsx, src/components/Forms/RecruitForm/index.tsx, src/components/HotArticlesPreview/index.tsx, src/components/PreviewErrorCard/index.tsx, src/components/RecruitsPreview/index.tsx, src/pages/main/index.tsx, src/services/article/apis.ts, src/services/article/hooks.ts, src/services/lunch/hooks.ts, src/services/recruit/apis/getRecruits.ts, src/services/recruit/hooks/useRecruits.ts, src/utils/createAuthGuard.tsx, src/utils/createNoIndexPageMetaData.ts
- 리쿠르팅 수정 폼 테스트
- 리쿠르팅 생성 폼 테스트
- 메인 페이지 UI 버그 수정
- 로딩 / 에러 / 성공 데이터가 동시에 나오는 버그
- 메인 페이지 SSR -> ISR
=> 리쿠르팅 수정/생성 Form 테스트, 메인 페이지 UI버그, 메인 페이지 ISR로 변경

cypress/integrations/pages/certification/intro-student-certification.cy.ts, cypress/integrations/pages/certification/student-certification.cy.ts, cypress/integrations/pages/recruits/recruit-detail.cy.ts, src/components/GlobalModal/useModal.ts, src/components/ModalContent/RecruitParticipantDetail/index.tsx, src/components/Recruit/Recruit/RecruitContactLink.tsx, src/components/Recruit/Recruit/RecruitTabs/RecruitParticipantsProgressDetail.tsx, src/components/Recruit/Recruit/RecruitTabs/RecruitTabsContent.tsx, src/components/RecruitApplicants/RecruitApplicantsDetail/index.tsx, src/components/RecruitApplicants/RecruitMembersAvatars/index.tsx, src/mocks/handlers/member/index.ts, src/mocks/handlers/recruit/apis/mockCreateRecruit.ts, src/mocks/handlers/recruit/apis/mockGetRecruitDetail.ts, src/mocks/handlers/recruit/apis/mockGetRecruitParticipants.ts, src/mocks/handlers/recruit/apis/mockUpdateRecruit.ts, src/mocks/handlers/recruit/data.ts, src/mocks/handlers/recruit/index.tsx, src/pages/recruits/[recruitId]/index.tsx, src/react-query/common/queryClient.ts, src/services/article/hooks.ts, src/services/lunch/hooks.ts, src/services/recruit/hooks/useRecruits.ts, src/stories/pages/recruit/RecruitCreatePage.stories.tsx, src/stories/pages/recruit/RecruitDetailPage.stories.tsx, src/stories/pages/recruit/RecruitEditPage.stories.tsx, src/styles/utils/resetStyle.ts, src/utils/client-routes/recruits.ts
- 리쿠르팅 디테일 페이지에서도 참여자 아바타 클릭시 상세 모달 팝업
- 참여자 상세정보 모달 리팩터링
- 글로벌 모달 api `openModal`의 componentProps type 수정 (upwrap Partial)
=> 리쿠르팅 디테일 페이지 참여자 상세 모달 추가, 테스트

.storybook/preview.tsx, cypress/component/forms/RecruitApplyForm.cy.tsx, cypress/component/forms/RecruitForm.cy.tsx, cypress/integrations/pages/recruits/recruit-apply.cy.ts, cypress/integrations/pages/recruits/recruit-detail.cy.ts, cypress/support/commands.ts, src/components/Common/SelectBox/index.tsx, src/components/Forms/RecruitApplyForm/Fields/AnswerToRecruitAuthor/index.tsx, src/components/Forms/RecruitApplyForm/Fields/RecruitPartToApply/index.tsx, src/components/Forms/RecruitApplyForm/index.tsx, src/components/Forms/RecruitForm/Fields/QuestionToApplicants/index.tsx, src/mocks/handlers/recruit/apis/mockApplyRecruit.ts, src/mocks/handlers/recruit/apis/mockCompleteRecruit.ts, src/mocks/handlers/recruit/index.tsx, src/pages/recruits/[recruitId]/apply/index.tsx, src/pages/recruits/index.tsx, src/react-query/common/queryKeys.ts, src/services/recruit/apis/getRecruits.ts, src/services/recruit/hooks/useRecruits.ts, src/services/recruit/utils/types.ts, src/stories/pages/recruit/RecruitApplyPage.stories.tsx, src/stories/pages/recruit/RecruitCreatePage.stories.tsx, src/stories/pages/recruit/RecruitDetailPage.stories.tsx, src/stories/pages/recruit/RecruitEditPage.stories.tsx, src/utils/client-routes/recruits.ts
- 리쿠르팅 신청 스토리, 테스트 작성
- 리쿠르팅 신청 누락된 validation 추가
=> 리쿠르팅 신청하기 테스트

cypress/component/forms/RecruitApplyForm.cy.tsx, cypress/integrations/pages/recruits/recruit-application.cy.ts, cypress/integrations/pages/recruits/recruit-my-application.cy.ts, src/mocks/handlers/recruit/apis/mockApproveRecruitApplication.ts, src/mocks/handlers/recruit/apis/mockCancelRecruitApplication.ts, src/mocks/handlers/recruit/apis/mockGetMyRecruitApplication.ts, src/mocks/handlers/recruit/apis/mockGetRecruitApplication.ts, src/mocks/handlers/recruit/apis/mockRejectRecruitApplication.ts, src/mocks/handlers/recruit/data.ts, src/mocks/handlers/recruit/index.tsx, src/pages/recruits/[recruitId]/applications/[recruitApplicationId]/index.tsx, src/pages/recruits/[recruitId]/applications/mine/index.tsx, src/react-query/common/queryKeys.ts, src/services/recruit/hooks/useAppliedRecruits.ts, src/services/recruit/hooks/useCancelRecruitApplication.ts, src/stories/pages/profile/AppliedRecruitsPage.stories.tsx, src/stories/pages/recruit/RecruitApplicationPage.stories.tsx, src/stories/pages/recruit/RecruitMyApplicationPage.stories.tsx, src/stories/utils/createMswParameters.ts, src/utils/client-routes/recruits.ts
- 리쿠르팅 신청서 Form 테스트
- 리쿠르팅 내 신청서 페이지 테스트
- 리쿠르팅 신청서 페이지 테스트
=> 리쿠르팅 신청서 테스트

src/utils/client-routes/recruit.ts
=> 리쿠르팅 생성 페이지 pathname 수정

package.json, src/components/Forms/PortfolioForm/index.tsx, src/components/Recruit/Recruit/RecruitTabs/RecruitParticipantsProgressDetail.tsx, src/mocks/handlers/recruit/apis/mockGetJoinedRecruits.ts, src/mocks/handlers/recruit/apis/mockGetRejectedRecruitApplicants.ts, src/react-query/common/queryKeys.ts, src/styles/utils/resetStyle.ts, src/test-utils/testing-library-utils.tsx
- sharp devDependencies -> dependencies로 변경
- lint error 해결
=> sharp dependencies로 추가

src/mocks/handlers/recruit/apis/mockApproveRecruitApplication.ts, src/mocks/handlers/recruit/apis/mockRejectRecruitApplication.ts, src/services/recruit/apis/approveRecruitApplication.ts, src/services/recruit/apis/rejectRecruitApplication.ts
=> API http method 수정

src/mocks/handlers/recruit/apis/mockGetRejectedRecruitApplicants.ts, src/services/recruit/apis/getRejectedRecruitApplicants.ts
- 거절한 리쿠르팅 신청자 목록 API Response 불일치 수정
=> 거절한 리쿠르팅 신청자 목록 Response 수정

src/pages/recruits/[recruitId]/applications/rejected/index.tsx
- 거절한 리쿠르팅 신청자 목록 페이지의 앱 내부의 Backward 버튼 path 수정
=> 거절한 리쿠르팅 신청자 목록 페이지 Backward 버튼 버그 수정

src/components/Forms/StudentCertificationForm/Fields/Quiz/Question/Blank.tsx, src/components/Forms/StudentCertificationForm/Fields/Quiz/Question/QuestionMap.tsx, src/components/Forms/StudentCertificationForm/Fields/Quiz/Question/index.tsx
- 질문 힌트로 제공되는 문구의 빈칸이 한글인지 영문인지에 따라 색상으로 힌트 제공
=> 학생 인증 Blank 한글/영문에 따라 색상으로 힌트 제공

src/components/Article/ArticleMain.tsx, src/components/ArticleCard/ArticleCard.tsx, src/components/ArticleCard/HotArticleCard.tsx, src/components/Recruit/Recruit/RecruitTitle.tsx, src/components/Recruit/RecruitCard/RecruitCardTitle.tsx
- 리쿠르팅, 게시글 제목의 FontFamily 를 Pretendard로 변경
=> 리쿠르팅, 게시글 제목의 FontFamily 업데이트

package.json, src/components/RouterProgress/index.tsx, src/pages/_app.tsx, yarn.lock
- 클라이언트 사이드 네비게이션 중에 상단에 노출되는 ProgressBar UI 추가
=> Client side navigation progressbar 추가

src/components/Article/ArticleMain.tsx, src/components/ArticleCard/ArticleCard.tsx, src/components/ArticleCard/HotArticleCard.tsx, src/components/ArticleCard/HotArticleCardSkeleton.tsx, src/components/ModalContent/ImageViewer/ImageLayer.tsx, src/components/ModalContent/ImageViewer/ViewerMain.tsx, src/mocks/handlers/article/apis/mockGetArticleDetail.ts, src/mocks/handlers/article/data.ts, src/services/article/utils/types.ts
- #275 
- 게시글 카드, 핫 게시글 카드에 썸네일 적용
=> 게시글 카드에 썸네일 적용

src/components/ModalContent/ImageViewer/ImageLayer.tsx
=> Image viewer initial scale 버그

src/components/BreadCrumbs/BreadCrumbs.stories.tsx, src/components/BreadCrumbs/index.tsx, src/components/Forms/MyInfoEditForm/index.tsx, src/components/Layout/RecruitDetailLayout.tsx, src/components/TitleBar/DefaultTitleBar.tsx, src/components/TopBar/index.tsx, src/pages/articles/[articleId]/index.tsx, src/pages/articles/categories/[categoryId]/index.tsx, src/pages/hot-articles/index.tsx, src/pages/profile/[userId]/index.tsx, src/pages/profile/applied-recruits/[recruitCategoryName]/index.tsx, src/pages/profile/my-articles/index.tsx, src/pages/profile/my-scraps/index.tsx, src/pages/profile/myinfo-settings/account/delete.tsx, src/pages/profile/myinfo-settings/is-major/edit.tsx, src/pages/profile/myinfo-settings/nickname/edit.tsx, src/pages/profile/myinfo-settings/ssafy-basic-info/edit.tsx, src/pages/profile/myinfo-settings/track/edit.tsx, src/pages/recruits/[recruitId]/applications/[recruitApplicationId]/index.tsx, src/pages/recruits/[recruitId]/applications/index.tsx, src/pages/recruits/[recruitId]/applications/mine/index.tsx, src/pages/recruits/[recruitId]/applications/rejected/index.tsx, src/pages/recruits/[recruitId]/apply/index.tsx, src/pages/recruits/[recruitId]/index.tsx, src/styles/utils/palettes.ts
- #283
- `BreadCrumbs` 관련 변경사항은 이슈 참고
- `<TitleBar />` footer props 추가
=> BreadCrumbs 추가 및 필요한 페이지에 적용

src/pages/profile/myinfo-settings/index.tsx, src/pages/recruits/[recruitId]/apply/index.tsx
- #283 
- 누락된 BreadCrumbs 추가
- 리쿠르팅 신청 완료시 리다이렉션 가이드의 내 프로필로 이동 버튼 클릭시
- 바꾸기 전: 내 프로필로 이동
- 바꾼 후: 내 프로필의 리쿠르팅 신청 목록으로 이동
=> 누락된 BreadCrumbs 추가, 리쿠르팅 신청 완료시 리다이렉션 가이드 업데이트

src/pages/profile/myinfo-settings/account/delete.tsx, src/utils/axios.ts, src/utils/clearPrivateData.ts
- #287 
- close #287
- 회원 탈퇴 재확인 모달 추가
=> 회원 탈퇴 재확인 모달

src/components/Recruit/Recruit/RecruitApplyLink.tsx
=> 로그인 하지 않은 유저가 리쿠르팅 신청 버튼 클릭시 로그인 안내 모달 팝업

src/components/ArticleCard/ArticleCardLink.tsx, src/components/ArticleCard/ArticleCardSkeleton.tsx, src/components/ArticleCard/HotArticleCardSkeleton.tsx, src/components/Common/Icon/index.tsx, src/components/Common/Scroll/index.tsx, src/components/Pagination/Pagination.stories.tsx, src/components/Pagination/index.tsx, src/hooks/useCallbackRef.ts, src/utils/array.ts
=> 페이지네이션 컴포넌트

src/components/Profile/JoinedRecruitsTabContent/index.tsx, src/pages/profile/applied-recruits/[recruitCategoryName]/index.tsx, src/pages/profile/my-scraps/index.tsx
- #291
- 내가 스크랩한 리쿠르팅 페이지네이션 적용
- 신청한 프로젝트 및 스터디 목록의 예외 UI 버그 해결
- 내가 신청한 리쿠르팅의 페이지네이션 매직넘버 들어가있던것 제거
=> 누락된 페이지네이션 적용 및 UI 버그

src/pages/profile/myinfo-settings/account/delete.tsx
=> 회원 탈퇴 안내 메세지 추가

src/components/ArticleComment/ArticleComment.stories.tsx, src/components/ArticleComment/CommentContent.tsx, src/services/member/hooks/useSetMyInfo.ts, src/utils/escapeHtmlString.ts, src/utils/regex.ts, src/utils/sanitizeHtml.ts
- #300
- 댓글에 포함된 링크를 a태그로 렌더링
- 댓글 content를 텍스트만 렌더링하는 방식에서  `dangerouslySetInnerHTML`로 렌더링하도록 변경
- a태그로 감싸기 전에 특수문자 이스케이프처리
=> 댓글 content에 링크가 포함되어있으면 앵커 태그로 렌더링

src/components/ArticleComment/ArticleComment.stories.tsx, src/components/ArticleComment/CommentContent.tsx, src/components/ArticleComment/index.tsx
- #302 
- 익명 + 내 댓글인 경우 `(나)` 표시
- (수정됨) 위치를 콘텐츠 영역에서 헤더 영역으로 변경
=> 댓글 UI 업데이트

src/utils/clearPrivateData.ts
- 토큰 재발급 실패로 인한 자동 로그아웃시 `TopBar`의 로그인버튼이 노출되지 않고 계속 Spinner가 보이는 문제가 있음
- `removeQueries`는 구독 컴포넌트에게 변경을 알리지 않기 때문에 발생
=> 로그아웃 or 회원탈퇴시 `removeQueries` -> `resetQueries`로 변경

src/components/NameCard/index.tsx, src/services/member/utils/types.ts
-  ssafyInfo 타입 수정 (null 가능으로 변경)
=> SsafyInfo 타입 수정

src/components/Forms/ArticleCommentForm/index.tsx, src/components/Forms/ArticleForm/index.tsx
- #309
- 게시글 및 게시글댓글의 익명값을 기본적으로 `true`로 설정
=> 게시글, 게시글 댓글 익명을 기본값으로 변경

src/pages/legal/[termSequence]/index.tsx
- 약관 페이지 path parameter를 `termId` -> `termSequence`로 변경
- `termSequence`는 무조건 1부터 시작하므로
=> 약관 페이지 path parameter 변경

src/components/Lunch/LunchCard/LunchCardMenuDescription.tsx
- 점심 이미지 순서 1 ~ 3에 대해 priority어트리뷰트 true로 설정
=> 점심 이미지 순서 1~3 priority 설정

src/components/Common/Icon/index.tsx, src/components/Common/IntersectionArea/index.tsx, src/pages/intro/student-certification/index.tsx
- SSAFY 학생 인증 페이지에 스크롤 다운 인디케이터 추가
=> SSAFY 학생 인증 페이지에 스크롤 다운 인디케이터 추가

src/components/Clock/TimeViewer.stories.tsx, src/components/Clock/index.tsx, src/utils/getDuration.ts, src/utils/isBetweenTimes.ts
- #317
- 입실 및 퇴실 시간 안내를 위한 시계 추가
[스토리북 링크]()
=> 입실 및 퇴실 시간 안내 (홈페이지)

src/pages/legal/[termSequence]/index.tsx
=> legal 페이지 metadata 추가

src/components/Clock/SeoulTimeViewer.stories.tsx, src/components/Clock/index.tsx, src/pages/profile/my-scraps/index.tsx, src/utils/DayOfWeek.ts, src/utils/getSeoulDate.ts, src/utils/gtag.ts, src/utils/toSeoulDate.ts
- 시계 타임존 Asia/Seoul로 변경
- 주말에 입퇴실 안내 메세지가 나오지 않도록 변경
- 마이스크랩 페이지의 탭 트리거 버튼 레이아웃이 의도한대로 동작하지 않는 버그 해결 (사파리 브라우저)
=> 시계 타임존 설정, 주말 안내 메세지 제거, 마이스크랩 레이아웃 버그

src/components/Clock/index.tsx
- 시계 하이드레이션 오류 메세지 suppress
- [참고](https://react.dev/reference/react-dom/client/hydrateRoot#suppressing-unavoidable-hydration-mismatch-errors)
=> 시계 하이드레이션 오류 무시

src/services/meta/apis/getTermsOfService.ts, src/utils/axios.ts
=> 토큰 재발급 무한루프시 강제 로그아웃

src/utils/axios.ts
This reverts commit fce4bec34af0e914abc2680d8cab9c45c0c00026.
=> Revert 무한 재발급 감지시 로그아웃 호출

src/components/Editor/Editor.tsx
=> URL 붙여넣기시 링크 자동삽입

src/pages/admin/index.tsx, src/pages/admin/page-revalidation/index.tsx, src/pages/api/revalidate.ts, src/services/admin/apis/index.ts, src/services/admin/apis/revalidatePage.ts, src/services/admin/hooks/index.ts, src/services/admin/hooks/useRevalidatePage.ts, src/utils/admin/adminEndpoints.ts, src/utils/constants.ts, src/utils/gtag.ts
- #329
- Manual Page Revalidation 어드민 페이지 추가
=> Manual Page Revalidation 어드민 페이지 추가

src/components/Common/Avatar/SingleAvatar.tsx, src/components/Name/index.tsx, src/mocks/handlers/member/apis/mockGetMyInfo.ts, src/mocks/handlers/member/data.ts, src/mocks/handlers/member/index.ts, src/pages/admin/index.tsx, src/pages/admin/page-revalidation/index.tsx
- `lg`사이즈 크기 조절 (폰트 40 -> 28, 아바타 40 -> 36)
=> `<Avatar />`, `<Name />` 크기 조절

next.config.js
=> sentry org 변경

src/components/Common/Toast/LoadingToast.tsx, src/components/Common/Toast/ServerErrorToast.tsx, src/components/Common/Toast/SuccessToast.tsx, src/components/Common/Toast/ToastRoot.tsx, src/components/Editor/ToolBarItem.tsx, src/components/Forms/ArticleForm/Fields/ArticleOptions.tsx, src/pages/auth/sign-in/index.tsx, src/services/s3/hooks/useImageUpload.ts, src/services/s3/utils/openImageUploader.ts, src/styles/GlobalStyles.tsx, src/utils/customToast.tsx, src/utils/toWebp.ts, src/utils/toast-classnames/index.ts
- 이미지 변환중 업로드 불가능하게 막고 인디케이터 표시
- 애플 로그인 삭제 (임시)
=> 애플로그인 삭제, 이미지 변환 인디케이터 추가

src/styles/utils/resetStyle.ts
- # 
- `white-space: nowrap` 제거
=> button reset style 변경

src/components/Common/TextInput/index.tsx, src/components/Editor/Editor.tsx, src/components/Forms/ArticleCommentForm/index.tsx, src/services/article/utils/articleCss.ts, src/styles/GlobalStyles.tsx
=> 인풋 폰트 사이즈 조정

package.json, src/components/Editor/Editor.tsx, yarn.lock
https://github.com/getsentry/sentry-javascript/security?mkt_tok=Nzc2LU1KTi01MDEAAAGPNi1L-lBn5ryLfYAVH0ec3VdJbwEt9OcdEMBvKPFyigS55p0fLEBwsCRCAxVbMGvPjlHSlxk5fswhpdHVtR7cC3MaxM7KjyWVcw--lYVIYeE
=> Sentry Update

src/components/Forms/UserRegisterForm/index.tsx, src/hooks/useSignOutReconfirmModal.ts, src/pages/auth/register/index.tsx
=> 회원가입 취소 UI 추가

package.json, src/components/Common/SelectBox/classnames.ts, src/components/Common/SelectBox/index.tsx, src/components/Forms/ArticleForm/Fields/ArticleCategories.tsx, src/components/Forms/ArticleForm/index.tsx, src/components/Forms/ArticleForm/utils/types.ts, src/pages/articles/[articleId]/edit.tsx, src/pages/articles/new/index.tsx, yarn.lock
- #343 
- #345
- 게시글 작성시 카테고리 선택 가능하도록 변경
- 게시글 Form의 내용변경이 없으면 제출 버튼 비활성화
- 게시글 수정시 Form의 변경사항이 추가적으로 체크 (Deep Equal로 비교 후 안내메세지 팝업)
=> 게시글 작성시 카테고리 선택가능하도록 변경, 게시글 수정시 내용 변경 없으면 안내 메세지 팝업

src/services/s3/apis/uploadImageToS3.ts, src/services/s3/hooks/useImageUpload.ts, src/services/s3/utils/openImageUploader.ts, src/utils/toWebp.ts
- #348
- 이미지 업로드시 Webp변환 제거, gif타입 이미지 업로드 가능하도록 변경
=> 이미지 업로드시 Webp 변환 제거, 업로드 이미지 타입중 GIF 추가

src/components/Article/ArticleMain.tsx, src/components/Editor/Editor.stories.tsx
- 게시글 상세보기시 제목 UI 버그 수정
- ToolBar 스토리 추가
=> 게시글 상세보기시 제목 UI 버그 수정, ToolBar 스토리 추가

src/components/Footer/index.tsx, src/components/SearchBar/index.tsx, src/pages/articles/new/index.tsx, src/pages/hot-articles/index.tsx, src/services/common/utils/searchBar.ts
- 핫 게시글 페이지 리팩터링 (게시글 목록 페이지에서 공통적으로 사용하는 `SearchBar`분리 및 키워드 유효성 검사)
- 핫 게시글 페이지에 게시글 작성 버튼 추가
=> 핫 게시글 페이지 리팩터링, 핫 게시글 페이지에 게시글 작성 버튼 추가

src/components/ModalContent/ImageViewer/ImageLayer.tsx
- 이미지 뷰어의 scaleFactor 0.5 -> 0.9로 업데이트
=> ImageViewer scaleFactor 업데이트

src/pages/recruits/[recruitId]/applications/index.tsx
- `<BreadCrumbs />` UI 추가에 따른 `<RecruitCompletedBar />`컴포넌트 레이아웃 버그 수정
=> RecruitCompletedBar 레이아웃 수정

src/utils/array.ts, src/utils/sanitizeHtml.ts
- `deduplicate` array utility 추가
- dompurify hook 수정
- 중복 어트리뷰트 제거
- 서버에서도 실행되도록 `isClient` 조건문 제거
=> Dompurify 훅 (`a`엘리먼트) 수정

src/components/ArticleCard/ArticleCard.tsx, src/components/ArticleCard/HotArticleCard.tsx
- 게시글 카드 Thumbnail fallback 추가
=> 게시글 카드 Thumbnail fallback 추가

src/components/ArticleCard/ArticleCard.tsx, src/components/ArticleCard/HotArticleCard.tsx
=> 게시글 카드 썸네일 CSS 수정

src/components/Lunch/LunchMenusPreview/LunchMenusPreviewMenuDescription.tsx
- 홈페이지의 LunchMenuPreview display text 수정 (메뉴 이름에 `dd` suffix가 붙어있었음)
=> 홈페이지의 LunchMenuPreview display text 수정

src/components/ModalContent/ImageViewer/ViewerMain.tsx
- 이미지 뷰어의 `maxScale`값 수정
- 최초 이미지의 `scale`값이 `maxScale`보다 커지는 문제가 있음 -> `maxScale`값을 최초 이미지 scale값보다 큰 값으로 조절
=> image-viewer maxScale값 수정

src/react-query/common/queryKeys.ts
`/notification/*` -> `/notifications/*`
=> 알림 endpoint 수정

src/components/Notification/NotificationItem.tsx
=> 알림 메세지 style 업데이트

src/components/Notification/NotificationItem.tsx, src/pages/notifications/index.tsx
=> 알림메세지 전송 날짜 ui 추가

src/services/article/utils/articleCss.ts
- #370 
- list item의 padding 기본값 제거
- list item의 ::before content (custom marker) 제거하고 기본 marker 사용
=> 에디터와 게시글의 List Item Style 수정

src/services/article/utils/articleCss.ts
=> articleCss 수정
